module.exports = {
	"400": "Bad Request",
	"401": "Unauthorized",
	"403": "Forbidden",
	"404": "Not Found",
	"405": "Method Not Allowed",
	"429": "Too Many Requests",
	"500": "Internal Server Error",
	"503": "Service Unavailable",
	"2000": "messages/voice call sent successfully",
	"2001": "message/voice call has been successfully scheduled",
	"4000": "Numeric Sender IDs are not allowed",
	"4001": "the recipient field, sender field and message field must not be empty",
	"4002": "make sure schedule date is not empty when is_schedule field is true",
	"4003": "the sender must not be greater than 11 in length",
	"4004": "credit is not enough to send message to recipients",
	"4005": "the scheduled time should be more than an hour from now",
	"4006": "either message field or message_id field should be empty",
	"4007": "message id provided does not exist",
	"4008": "either some of the groups has no contacts or group does not exist",
	"4009": "either voice file or voice_id field should be empty (only one should not be empty)",
	"4010": "file size should not be greater than 5MB",
	"4011": "an error occurred when uploading the file. try again",
	"4012": "the bit rate of the voice is too high to be sent to a phone",
	"4013": "voice id does not exist",
	"4014": "Sender ID is not registered. Please contact our support team via senderids@mnotify.com or call 0200896265 for assistance",
	"4015": "Sender Name and Purpose must not be empty"
}